#spring.application.name=identity-service
server:
  port: 8001
#  servlet:
#    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/test_btl"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "TgxvdxikRZHZ2cuJzW2ovQHn2iVTROFecLmYHi8ZJRe8cWejAU7WF+rw4zaInvgL"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: "them api key"
